#########################################################################
# Title:         Saltbox: Sanity Check | Skipped Tags                   #
# Author(s):     salty                                                  #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Skipped Tags | Print Skipped Tags
  debug:
    msg: "{{ ansible_skip_tags }}"
