#########################################################################
# Title:         Saltbox: Cockpit Role                                  #
# Author(s):     CHAIR/Raneydazed                                       #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Check if 'cockpit_socket' exists
  ansible.builtin.stat:
    path: "{{ cockpit_paths_socket_location }}"
  register: cockpit_socket

- name: Stop existing 'cockpit_socket'
  ansible.builtin.systemd:
    state: stopped
    name: cockpit.socket
  when: cockpit_socket.stat.exists

- name: Create directories
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/directories/create_directories.yml"

- name: Import 'cockpit_socket'
  ansible.builtin.template:
    src: listen.conf.j2
    dest: "{{ cockpit_paths_socket_location }}"
    mode: "0664"
    force: true

- name: Import 'cockpit_config'
  ansible.builtin.template:
    src: cockpit.conf.j2
    dest: "{{ cockpit_paths_config_location }}"
    mode: "0664"
    force: true

- name: Import 'cockpit_traefik'
  ansible.builtin.template:
    src: cockpit.yml.j2
    dest: "{{ cockpit_paths_traefik_location }}"
    mode: "0775"
    force: true

- name: Change traefik file ownership
  ansible.builtin.file:
    path: "{{ cockpit_paths_traefik_location }}"
    owner: "{{ uid }}"
    group: "{{ gid }}"
  when:
    - not continuous_integration
    # - not cockpit_socket.stat.exists

- name: Install Cockpit from backports
  ansible.builtin.apt:
    name: cockpit
    default_release: "{{ ansible_distribution_release }}-backports"
    update_cache: yes
  when: 
    - not cockpit_socket.stat.exists
    - not continuous_integration

- name: Load 'cockpit_socket'
  ansible.builtin.systemd:
    name: cockpit.socket
    state: started
    enabled: yes
    daemon_reload: true
  when: not continuous_integration
