#########################################################################
# Title:         Saltbox: Cockpit Role                                  #
# Author(s):     CHAIR/Raneydazed                                       #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Install Cockpit from backports
  ansible.builtin.apt:
    name: cockpit
    default_release: "{{ ansible_distribution_release }}-backports"
    update_cache: yes

- name: Enable Cockpit service
  ansible.builtin.systemd:
    name: cockpit.socket
    state: started
    enabled: yes
    daemon_reload: yes
