#########################################################################
# Title:         Saltbox: Nvidia | Docker Tasks                         #
# Author(s):     desimaniac, l3uddz                                     #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Docker | Remove old repository list
  ansible.builtin.file:
    path: "{{ nvidia_docker_runtime_apt_repo_file_old }}"
    state: absent

- name: Docker | Add 'nvidia-container-toolkit' APT Repo Key
  ansible.builtin.get_url:
    url: "{{ nvidia_docker_runtime_apt_key_url }}"
    dest: /etc/apt/trusted.gpg.d/nvidia.asc
    mode: "0644"
    force: true
  register: result
  retries: "{{ '0' if (not continuous_integration) else '5' }}"
  delay: 10
  until: result is succeeded

- name: Docker | Add 'nvidia-container-toolkit' APT list
  ansible.builtin.apt_repository:
    repo: "{{ item }}"
    filename: "{{ nvidia_docker_runtime_apt_repo_file }}"
    state: present
    mode: "0644"
    update_cache: true
  loop: "{{ lookup('ansible.builtin.url', nvidia_docker_runtime_apt_repo_list_url, wantlist=True) | regex_replace('^deb https', 'deb [signed-by=/etc/apt/trusted.gpg.d/nvidia.asc] https') }}"
  when: not item.startswith('#')

- name: Docker | Remove 'nvidia-container-runtime'
  ansible.builtin.apt:
    name: "nvidia-container-runtime"
    state: absent

- name: Docker | Remove 'nvidia-container-toolkit'
  ansible.builtin.apt:
    name: "nvidia-container-toolkit"
    state: absent

- name: Docker | Install 'nvidia-container-toolkit'
  ansible.builtin.apt:
    name: "nvidia-container-toolkit"
    update_cache: true
    state: present

- name: Docker | Create '/dev/char' symlinks
  ansible.builtin.shell: nvidia-ctk system create-dev-char-symlinks --create-all

- name: Docker | Import '71-nvidia-dev-char.rules'
  ansible.builtin.copy:
    src: 71-nvidia-dev-char.rules
    dest: "/lib/udev/rules.d/71-nvidia-dev-char.rules"
    owner: "root"
    group: "root"
    mode: "0644"

- name: Docker | Populate Service Facts
  ansible.builtin.service_facts:

- name: Docker | Get Docker service state
  ansible.builtin.set_fact:
    docker_service_running: "{{ (services['docker.service'] is defined) and (services['docker.service']['state'] == 'running') }}"

- name: Docker | Gather list of running Docker containers
  ansible.builtin.shell: "docker ps --format '{{ '{{' }} .Names{{ '}}' }}' | xargs echo -n"
  register: docker_running_containers
  ignore_errors: true
  when: docker_service_running

- name: Docker | Stop all running Docker containers
  ansible.builtin.shell: "docker stop {{ docker_running_containers.stdout }}"
  ignore_errors: true
  when: docker_service_running and (docker_running_containers.stdout | trim | length > 0)

- name: Docker | Stop docker service
  ansible.builtin.systemd_service:
    name: docker
    state: stopped
  when: docker_service_running

# https://github.com/linkernetworks/vortex-installer/blob/master/roles/common/tasks/nvidia-docker.yml
- name: Docker | Add runtime to '/etc/docker/daemon.json'
  ansible.builtin.shell: "{{ nvidia_docker_runtime_docker_daemon_json_jq_command }}"

- name: Docker | Start docker service
  ansible.builtin.systemd_service:
    name: docker
    state: started
  when: docker_service_running

- name: Docker Service Running
  when: docker_service_running and (docker_running_containers.stdout | trim | length > 0)
  block:
    - name: "Docker | Initialize Gluetun variable"
      ansible.builtin.set_fact:
        docker_containers_gluetun: []

    - name: "Docker | Identify any Gluetun containers"
      ansible.builtin.set_fact:
        docker_containers_gluetun: "{{ docker_containers_gluetun + [item] }}"
      loop: "{{ docker_running_containers.stdout.split() }}"
      when: item in (gluetun_instances | default(['gluetun']))

    - name: "Docker | Re-start all previously running Gluetun containers"
      ansible.builtin.shell: "docker start {{ docker_containers_gluetun | join(' ') }}"
      when: (docker_containers_gluetun | length > 0)
      ignore_errors: true

    - name: "Docker | Wait for {{ docker_network_container_health_delay }} seconds"
      ansible.builtin.wait_for:
        timeout: "{{ docker_network_container_health_delay }}"

    - name: "Docker | Re-start all previously running Docker containers"
      ansible.builtin.shell: 'docker start {{ docker_running_containers.stdout }}'
      ignore_errors: true
