##########################################################################
# Title:         Saltbox: Radarr | Default Variables                     #
# Author(s):     desimaniac, salty                                       #
# URL:           https://github.com/saltyorg/Saltbox                     #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Basics
################################

radarr_name: radarr

################################
# Paths
################################

radarr_paths_folder: "{{ radarr_name }}"
radarr_paths_location: "{{ server_appdata_path }}/{{ radarr_paths_folder }}"
radarr_paths_folders_list:
  - "{{ radarr_paths_location }}"
radarr_paths_config_location: "{{ radarr_paths_location }}/config.xml"

################################
# Web
################################

radarr_web_subdomain: "{{ radarr_name }}"
radarr_web_domain: "{{ user.domain }}"
radarr_web_port: "7878"
radarr_web_url: "{{ 'https://' + radarr_web_subdomain + '.' + radarr_web_domain
                 if (reverse_proxy_is_enabled)
                 else 'http://localhost:' + radarr_web_port }}"

################################
# DNS
################################

radarr_dns_record: "{{ radarr_web_subdomain }}"
radarr_dns_zone: "{{ radarr_web_domain }}"

################################
# Traefik
################################

radarr_traefik_sso_middleware: "{{ traefik_default_sso_middleware }}"
radarr_traefik_middleware: "{{ traefik_default_middleware + ',' + radarr_traefik_sso_middleware
                            if (radarr_traefik_sso_middleware | length > 0) 
                            else traefik_default_middleware }}"
radarr_traefik_certresolver: "{{ traefik_default_certresolver }}"
radarr_traefik_enabled: true
radarr_traefik_api_enabled: true
radarr_traefik_api_endpoint: "`/api`"

################################
# API
################################

# default to blank
radarr_api_key:

################################
# THEME
################################

# Options can be found at https://github.com/gilbN/theme.park
radarr_themepark_enabled: false
radarr_themepark_theme: "{{ global_themepark_theme }}"
radarr_themepark_domain: "{{ global_themepark_domain }}"

################################
# Docker
################################

# Container
radarr_docker_container: "{{ radarr_name }}"

# Image
radarr_docker_image_pull: true
radarr_docker_image_tag: "release"
radarr_docker_image: "hotio/radarr:{{ radarr_docker_image_tag }}"

# Ports
radarr_docker_ports_defaults:
  - "{{ radarr_web_port }}"
radarr_docker_ports_custom: []
radarr_docker_ports: "{{ radarr_docker_ports_defaults
                         + radarr_docker_ports_custom
                      if (not reverse_proxy_is_enabled)
                      else [] + radarr_docker_ports_custom }}"

# Envs
radarr_docker_envs_default:
  PUID: "{{ uid }}"
  PGID: "{{ gid }}"
  UMASK: "002"
  TZ: "{{ tz }}"
  TP_DOMAIN: "{{ radarr_themepark_domain }}"
  TP_THEME: "{{ radarr_themepark_theme }}"
  TP_HOTIO: "true"
radarr_docker_envs_custom: {}
radarr_docker_envs: "{{ radarr_docker_envs_default
                        | combine(radarr_docker_envs_custom) }}"

# Commands
radarr_docker_commands_default: []
radarr_docker_commands_custom: []
radarr_docker_commands: "{{ radarr_docker_commands_default
                            + radarr_docker_commands_custom }}"

# Volumes
radarr_docker_volumes_default:
  - "{{ radarr_paths_location }}:/config"
  - "{{ server_appdata_path }}/scripts:/scripts"
  - "/mnt/unionfs/Media/Movies:/movies"
  - "/mnt:/mnt"
radarr_docker_volumes_custom: []
radarr_docker_volumes_theme:
  - "{{ radarr_paths_location }}/98-themepark.sh:/etc/cont-init.d/98-themepark"
radarr_docker_volumes: "{{ radarr_docker_volumes_default
                           + radarr_docker_volumes_custom
                           + docker_volumes_downloads_common
                        if not (radarr_themepark_enabled)
                        else radarr_docker_volumes_default
                           + radarr_docker_volumes_custom
                           + docker_volumes_downloads_common
                           + radarr_docker_volumes_theme }}"

# Devices
radarr_docker_devices_default: []
radarr_docker_devices_custom: []
radarr_docker_devices: "{{ radarr_docker_devices_default
                           + radarr_docker_devices_custom }}"

# Hosts
radarr_docker_hosts_default: []
radarr_docker_hosts_custom: []
radarr_docker_hosts: "{{ docker_hosts_common
                         | combine(radarr_docker_hosts_default)
                         | combine(radarr_docker_hosts_custom) }}"

# Labels
radarr_docker_labels_default: {}
radarr_docker_labels_custom: {}
radarr_docker_labels: "{{ docker_labels_common
                          | combine(radarr_docker_labels_default)
                          | combine(radarr_docker_labels_custom) }}"

# Hostname
radarr_docker_hostname: "{{ radarr_name }}"

# Networks
radarr_docker_networks_alias: "{{ radarr_name }}"
radarr_docker_networks_default: []
radarr_docker_networks_custom: []
radarr_docker_networks: "{{ docker_networks_common
                            + radarr_docker_networks_default
                            + radarr_docker_networks_custom }}"

# Capabilities
radarr_docker_capabilities_default: []
radarr_docker_capabilities_custom: []
radarr_docker_capabilities: "{{ radarr_docker_capabilities_default
                                + radarr_docker_capabilities_custom }}"

# Security Opts
radarr_docker_security_opts_default: []
radarr_docker_security_opts_custom: []
radarr_docker_security_opts: "{{ radarr_docker_security_opts_default
                                 + radarr_docker_security_opts_custom }}"

# Restart Policy
radarr_docker_restart_policy: unless-stopped

# State
radarr_docker_state: started
