##########################################################################
# Title:         Saltbox: Media Server | Default Variables               #
# Author(s):     salty                                                   #
# URL:           https://github.com/saltyorg/Saltbox                     #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
media_servers_enabled: ["plex"]
media_server_autoscan_enabled: true
