##########################################################################
# Title:         Saltbox: Custom                                         #
# Author(s):     salty                                                   #
# URL:           https://github.com/saltyorg/Saltbox                     #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
- name: Custom | Update apt cache
  ansible.builtin.apt:
    update_cache: true
  ignore_errors: true

- name: Custom | Install custom apt packages
  ansible.builtin.apt:
    state: latest
    name: "{{ item }}"
  ignore_errors: true
  loop: "{{ custom_apt }}"

- name: Custom | Install custom deb packages
  ansible.builtin.apt:
    state: present
    deb: "{{ item }}"
  ignore_errors: true
  loop: "{{ custom_deb }}"

- name: Install custom pip modules
  ansible.builtin.shell: "pip install {{ item }}"
  ignore_errors: true
  loop: "{{ custom_pip }}"
