#########################################################################
# Title:            Saltbox: cockpit | Default Variables                #
# Author(s):        CHAIR/Raneydazed                                    #
# URL:              https://github.com/saltyorg/Saltbox                 #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
################################
# Basics
################################

cockpit_name: cockpit

################################
# Paths
################################

cockpit_paths_socket_location: "/etc/systemd/system/cockpit.socket.d/listen.conf"
cockpit_paths_config_location: "/etc/cockpit/cockpit.conf"
cockpit_paths_traefik_location: "/opt/traefik/cockpit.yml"
cockpit_paths_folders_list:
  - "/etc/systemd/system/cockpit.socket.d"
  - "/etc/cockpit"
#   - "{{ cockpit_paths_listen_conf_location }}"
#   - "{{ cockpit_paths_socket_location }}"
#   - "{{ cockpit_paths_etc_conf_location }}"
#   - "{{ cockpit_paths_traefik_location }}"

################################
# Web
################################

cockpit_web_subdomain: "{{ cockpit_name }}"
cockpit_web_domain: "{{ user.domain }}"
cockpit_web_port: "1337"

################################
# DNS
################################

cockpit_dns_record: "{{ cockpit_web_subdomain }}"
cockpit_dns_zone: "{{ cockpit_web_domain }}"
cockpit_dns_proxy: "{{ dns.proxied }}"
cockpit_web_url: "{{ 'https://' + (cockpit_web_subdomain + '.' + cockpit_web_domain
                  if (cockpit_web_subdomain | length > 0)
                  else cockpit_web_domain) }}"
cockpit_web_url_http: "{{ 'http://' + (cockpit_web_subdomain + '.' + cockpit_web_domain
                       if (cockpit_web_subdomain | length > 0)
                       else cockpit_web_domain) }}"

################################
# Traefik
################################

cockpit_traefik_sso_middleware: "{{ traefik_default_sso_middleware }}"
cockpit_traefik_middleware_default: "{{ traefik_default_middleware }}"
cockpit_traefik_middleware_custom: ""
cockpit_traefik_certresolver: "{{ traefik_default_certresolver }}"
cockpit_traefik_enabled: true
cockpit_traefik_api_enabled: true
