#########################################################################
# Title:         Saltbox: Community Role                                #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Create Community directory
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: 0775
    recurse: yes
  with_items:
    - /opt/community

- name: Clone Community repo 'HEAD'
  git:
    repo: https://github.com/saltyorg/community.git
    dest: /opt/community
    clone: true
    version: HEAD
    force: true
  become: true
  become_user: "{{ user.name }}"
  ignore_errors: true
  register: community_clone_status

- name: Clone Community repo 'master'
  git:
    repo: https://github.com/saltyorg/community.git
    dest: /opt/community
    clone: true
    version: master
    force: true
  become: true
  become_user: "{{ user.name }}"
  when: community_clone_status is failed

- name: Import default files when missing
  copy:
    src: "{{ item }}"
    dest: "/opt/community/{{ (item | basename | splitext)[0] }}"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: 0775
    force: false
  with_fileglob:
    - /opt/community/defaults/*.*

- name: Force overwrite community ansible.cfg
  copy:
    src: "/opt/community/defaults/ansible.cfg.default"
    dest: "/opt/community/ansible.cfg"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: 0664
    force: true

- name: Activate Git Hooks
  shell: bash /opt/community/bin/git/init-hooks
  args:
    chdir: "/opt/community"
