#########################################################################
# Title:         Saltbox: Cloudflare | Subdomains | Add Subdomain       #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Subdomains | Add Subdomain | Cloudflare: Add '{{ saltbox_type }}' subdomain to '{{ fld.stdout }}'"
  cloudflare_dns:
    account_api_token: "{{ cloudflare.api }}"
    account_email: "{{ cloudflare.email }}"
    zone: "{{ fld.stdout }}"
    state: present
    solo: true
    proxied: "{{ dns.proxied | default('no') }}"
    type: A
    value: "{{ ip_address_public }}"
    record: "{{ saltbox_type }}"
