#########################################################################
# Title:         Saltbox: Cloudflare | Subdomains | Remove Subdomain    #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Subdomains | Remove Subdomain | Cloudflare: Remove 'saltbox' subdomain from '{{ fld.stdout }}'"
  cloudflare_dns:
    account_api_token: "{{ cloudflare.api }}"
    account_email: "{{ cloudflare.email }}"
    zone: "{{ fld.stdout }}"
    state: absent
    type: A
    record: "saltbox"
