#########################################################################
# Title:         Saltbox: Docker | Nvidia Tasks                         #
# Author(s):     salty                                                  #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Nvidia | Remove old repository list
  ansible.builtin.file:
    path: "{{ nvidia_docker_runtime_apt_repo_file_old }}"
    state: absent

- name: Nvidia | Remove '/etc/apt/keyrings/nvidia-container-toolkit-keyring.gpg'
  ansible.builtin.file:
    path: "/etc/apt/keyrings/nvidia-container-toolkit-keyring.gpg"
    state: absent

- name: Nvidia | Add 'nvidia-container-toolkit' APT Repo Key
  ansible.builtin.shell: "curl -fsSL {{ nvidia_docker_runtime_apt_key_url }} | sudo gpg --dearmor -o /etc/apt/keyrings/nvidia-container-toolkit-keyring.gpg"
  register: result
  retries: "{{ ansible_retry_count if (not continuous_integration) else ansible_retry_count_ci }}"
  delay: 10
  until: result is succeeded

- name: Nvidia | Add 'nvidia-container-toolkit' APT list
  ansible.builtin.apt_repository:
    repo: "{{ nvidia_docker_apt_repo_url }}"
    filename: "{{ nvidia_docker_runtime_apt_repo_file }}"
    state: present
    mode: "0644"
    update_cache: true

- name: Nvidia | Remove 'nvidia-container-runtime'
  ansible.builtin.apt:
    name: "nvidia-container-runtime"
    state: absent

- name: Nvidia | Install 'nvidia-container-toolkit'
  ansible.builtin.apt:
    name: "nvidia-container-toolkit"
    update_cache: true
    state: latest
