##########################################################################
# Title:         Saltbox: Global Variables                               #
# Author(s):     desimaniac, salty                                       #
# URL:           https://github.com/saltyorg/Saltbox                     #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Resources
################################

resources_tasks_path: "/srv/git/saltbox/resources/tasks"

################################
# Continuous Integration
################################

continuous_integration: false

################################
# Accounts
################################

cloudflare_is_enabled: "{{ (cloudflare is defined) and
                           (cloudflare is not none) and
                           (cloudflare | trim | length > 0) and
                           (cloudflare.email is defined) and
                           (cloudflare.email is not none) and
                           (cloudflare.email | trim | length > 0) and
                           (cloudflare.api is defined) and
                           (cloudflare.api is not none) and
                           (cloudflare.api | trim | length > 0) }}"

plex_account_is_enabled: "{{ (plex is defined) and
                             (plex is not none) and
                             (plex | trim | length > 0) and
                             (plex.user is defined) and
                             (plex.user is not none) and
                             (plex.user | trim | length > 0) and
                             (plex.pass is defined) and
                             (plex.pass is not none) and
                             (plex.pass | trim | length > 0) }}"

################################
# Role Conditionals
################################

nzbs_downloads_path_is_defined: "{{ (downloads is defined) and
                                    (downloads is not none) and
                                    (downloads | trim | length > 0) and
                                    (downloads.nzbs is defined) and
                                    (downloads.nzbs is not none) and
                                    (downloads.nzbs | trim | length > 0) }}"

use_nzbs: "{{ nzbs_downloads_path_is_defined }}"

torrents_downloads_path_is_defined: "{{ (downloads is defined) and
                                        (downloads is not none) and
                                        (downloads | trim | length > 0) and
                                        (downloads.torrents is defined) and
                                        (downloads.torrents is not none) and
                                        (downloads.torrents | trim | length > 0) }}"

use_torrents: "{{ torrents_downloads_path_is_defined }}"

feeder_mount_is_enabled: "{{ (mounts is defined) and
                             (mounts is not none) and
                             (mounts | trim | length > 0) and
                             (mounts.feeder is defined) and
                             (mounts.feeder is not none) and
                             (mounts.feeder | trim | length > 0) and
                             (mounts.feeder) }}"

rclone_remote_is_defined: "{{ (rclone is defined) and
                              (rclone is not none) and
                              (rclone | trim | length > 0) and
                              (rclone.remote is defined) and
                              (rclone.remote is not none) and
                              (rclone.remote | trim | length > 0) }}"

use_remote: "{{ feeder_mount_is_enabled or rclone_remote_is_defined }}"

use_nvidia: "{{ gpu.nvidia }}"

################################
# System
################################

server_root_path: "/"

server_appdata_path: "{{ server_root_path | regex_replace('\\/$', '') + '/opt' }}"

################################
# Paths
################################

transcodes_path: "{{ transcodes }}"

################################
# User
################################

uid: "{{ ansible_local.user[user.name].uid }}"

gid: "{{ ansible_local.user[user.name].gid }}"

vgid: "{{ ansible_local.group.video.gid }}"

################################
# Timezone
################################

tz: "{{ system.timezone
     if system is defined and
        system.timezone is defined and
        'auto' not in system.timezone | lower
     else ansible_local.timezone
        if ansible_local is defined and
            ansible_local.timezone is defined and
            ansible_local.timezone | trim | length > 0
     else 'Etc/UTC' }}"

################################
# Network
################################

ip_address_host: "0.0.0.0"

ip_address_localhost: "127.0.0.1"

ip_address_public: "{{ ansible_local.network.ip.public_ip | default(ansible_default_ipv4.address) }}"

ipv6_address_public: "{{ ansible_local.network.ip.public_ipv6 | default(ansible_default_ipv6.address) }}"

################################
# Reverse Proxy
################################

reverse_proxy_is_enabled: "{{ (user is defined) and
                              (user is not none) and
                              (user | trim | length > 0) and
                              (user.domain is defined) and
                              (user.domain is not none) and
                              (user.domain | trim | length > 0) and
                              (user.email is defined) and
                              (user.email is not none) and
                              (user.email | trim | length > 0) }}"

################################
# Theme
################################

# Options can be found at https://github.com/gilbN/theme.park
global_themepark_theme: organizr
global_themepark_domain: theme-park.dev

################################
# Traefik
################################

traefik_default_certprovider: "{{ 'cfdns' if not dns.zerossl else 'zerossl' }}"
traefik_default_tlsresolver: "{{ 'tlsresolver' if not dns.zerossl else 'zerossl-tls' }}"
traefik_default_certresolver: "{{ traefik_default_tlsresolver if (not cloudflare_is_enabled) or (traefik.tls) else traefik_default_certprovider }}"
traefik_default_middleware: "{{ 'secureHeaders@file,gzip' if (not traefik.hsts) else 'secureHeaders@file,gzip,hsts@file' }}" 
traefik_role_enabled: "{{ lookup('vars', role_name + '_traefik_enabled', default=False) }}"
traefik_tls: "{{ true if (not cloudflare_is_enabled) or (traefik.tls) else false }}"
traefik_subdomain: "{{ lookup('vars', role_name + '_web_subdomain', default=omit) }}"
traefik_domain: "{{ lookup('vars', role_name + '_web_domain', default=omit) }}"
traefik_router: "{{ lookup('vars', role_name + '_name', default=omit) }}"
traefik_host: "{{ traefik_subdomain + '.' + traefik_domain
               if (traefik_subdomain | length > 0)
               else traefik_domain }}"

################################
# Docker
################################

docker_volumes_downloads_nzbs: "{{ [downloads.nzbs + ':/downloads/nzbs']
                                if nzbs_downloads_path_is_defined
                                else [] }}"

docker_volumes_downloads_torrents: "{{ [downloads.torrents + ':/downloads/torrents']
                                    if torrents_downloads_path_is_defined
                                    else [] }}"

docker_volumes_downloads_common: "{{ docker_volumes_downloads_nzbs + docker_volumes_downloads_torrents }}"

docker_hosts_common: []

docker_labels_saltbox:
  - com.github.saltbox.saltbox_managed: "true"

docker_labels_traefik:
  - traefik.enable: "true"
  - '{ "traefik.http.routers.{{ traefik_router }}.entrypoints": "websecure" }'
  - '{ "traefik.http.routers.{{ traefik_router }}.service": "{{ traefik_router }}" }'
  - '{ "traefik.http.routers.{{ traefik_router }}.rule": "Host(`{{ traefik_host }}`)" }'
  - '{ "traefik.http.routers.{{ traefik_router }}.priority": "{{ lookup("vars", role_name + "_traefik_priority", default=omit) }}" }'
  - '{ "traefik.http.routers.{{ traefik_router }}.tls.options": "securetls@file" }'
  - '{ "traefik.http.routers.{{ traefik_router }}.tls.certresolver": "{{ lookup("vars", role_name + "_traefik_certresolver", default=omit) }}" }'
  - '{ "traefik.http.routers.{{ traefik_router }}.middlewares": "{{ lookup("vars", role_name + "_traefik_middleware", default=omit) }}" }'
  - '{ "traefik.http.services.{{ traefik_router }}.loadbalancer.server.port": "{{ lookup("vars", role_name + "_web_port", default=omit) }}" }'
  - '{ "traefik.http.services.{{ traefik_router }}.loadbalancer.server.scheme": "{{ lookup("vars", role_name + "_web_scheme", default=omit) }}" }'

docker_labels_common: "{{ docker_labels_saltbox | combine(docker_labels_traefik)
                       if (traefik_role_enabled)
                       else docker_labels_saltbox }}"

docker_networks_name_common: saltbox

docker_networks_common:
  - name: "{{ docker_networks_name_common }}"
    aliases:
      - "{{ lookup('vars', role_name + '_docker_networks_alias') }}"

dockerhub_is_enabled: "{{ (dockerhub is defined) and
                          (dockerhub is not none) and
                          (dockerhub | trim | length > 0) and
                          (dockerhub.user is defined) and
                          (dockerhub.user is not none) and
                          (dockerhub.user | trim | length > 0) and
                          (dockerhub.token is defined) and
                          (dockerhub.token is not none) and
                          (dockerhub.token | trim | length > 0) }}"

################################
# Cloudbox Version Manager
################################

cvm: https://cvm.saltbox.dev/version?url=

################################
# Backup
################################

backup_rclone_transfers: 4
backup_rclone_drive_chunk_size: 128M

reverse_proxy_apps:
  - traefik

torrent_apps:
  - deluge
  - delugevpn
  - qbittorrent
  - qbittorrentvpn
  - rutorrent
  - transmission
  - transmissionvpn
