#########################################################################
# Title:         Saltbox: Cloudplow Role                                #
# Author(s):     l3uddz, desimaniac, salty                              #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Stop Service
  include_tasks: "{{ resources_tasks_path }}/systemd/stop_service.yml"
  vars:
    _service_name: "{{ cloudplow_service_name }}"

- name: Create directory
  file:
    path: "{{ cloudplow_path }}"
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: 0775
    recurse: true

- name: Clone project git repo
  include_tasks: "{{ resources_tasks_path }}/git/clone_git_repo.yml"

- name: Install pip requirements
  pip:
    requirements: "{{ cloudplow_requirements_path }}"
    virtualenv_python: python3
    virtualenv: "{{ cloudplow_venv_path }}"
  become: true
  become_user: "{{ user.name }}"

- name: Set script as executable
  file:
    path: "{{ cloudplow_script_path }}"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: a+x

- name: Create script alias
  template:
    src: cloudplow.sh.j2
    dest: "{{ cloudplow_alias_path }}"
    mode: "0755"
    force: true

- name: Import Settings Task
  import_tasks: "subtasks/settings.yml"

- name: Import '{{ cloudplow_service_name }}.service'
  template:
    src: cloudplow.service.j2
    dest: "/etc/systemd/system/{{ cloudplow_service_name }}.service"
    mode: "0755"
    force: true

- name: Start service
  systemd:
    name: "{{ cloudplow_service_name }}"
    state: started
    enabled: true
    daemon_reload: true
