#########################################################################
# Title:         Saltbox: Authelia Role                                 #
# Author(s):     salty                                                  #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Import Redis Role"
  import_role:
    name: redis

- name: Install argon2_cffi python package
  pip:
    name: argon2_cffi
    executable: pip3

- name: Add DNS record
  include_tasks: "{{ resources_tasks_path }}/dns/tasker.yml"
  vars:
    dns_record: "{{ lookup('vars', role_name + '_dns_record') }}"
    dns_zone: "{{ lookup('vars', role_name + '_dns_zone') }}"

- name: Remove existing Docker container
  include_tasks: "{{ resources_tasks_path }}/docker/remove_docker_container.yml"

- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0775"
  with_items: "{{ lookup('vars', role_name + '_paths_folders_list') }}"

- name: Check if 'configuration.yml' exists
  stat:
    path: "{{ authelia_paths_location }}/configuration.yml"
  register: authelia_config_stat

- name: Check if 'users_database.yml' exists
  stat:
    path: "{{ authelia_paths_location }}/users_database.yml"
  register: authelia_user_config_stat

- name: "Generate Password Hash"
  shell: "docker run --rm authelia/authelia:latest authelia hash-password '{{ user.pass }}' | sed -n 's/^Password hash: //p'"
  register: authelia_password
  when: (not authelia_user_config_stat.stat.exists)

- name: Import default 'configuration.yml'
  template:
    src: configuration.yml.j2
    dest: "{{ authelia_paths_location }}/configuration.yml"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0775"
  when: (not authelia_config_stat.stat.exists)

- name: Import default 'users_database.yml'
  template:
    src: users_database.yml.j2
    dest: "{{ authelia_paths_location }}/users_database.yml"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0775"
  when: (not authelia_user_config_stat.stat.exists)

- name: Create Docker container
  include_tasks: "{{ resources_tasks_path }}/docker/create_docker_container.yml"
