#########################################################################
# Title:         Saltbox: Common Role                                   #
# Author(s):     l3uddz, desimaniac                                     #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: BTRFS Tasks
  include_tasks: "btrfs.yml"
  loop:
    - /opt
    - /mnt/local
  loop_control:
    loop_var: outer_item

- name: Create common directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0775"
  with_items:
    - /home/{{ user.name }}
    - /home/{{ user.name }}/logs
    - /home/{{ user.name }}/.config
    - /home/{{ user.name }}/.config/pip
    - /opt
    - /mnt/local
    - /mnt/local/Media
    - /mnt/local/Media/Movies
    - /mnt/local/Media/Music
    - /mnt/local/Media/TV

- name: "Import 'localhost.yml'"
  copy:
    src: "localhost.yml"
    dest: "/srv/git/saltbox/inventories/host_vars/localhost.yml"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: 0775

- name: Install required packages
  apt:
    state: present
    name:
      - apt-transport-https
      - ca-certificates
      - software-properties-common

- name: Add Ubuntu repositories
  apt_repository:
    repo: "{{ item }}"
    state: present
    update_cache: true
  with_items:
    - 'deb http://archive.ubuntu.com/ubuntu {{ ansible_distribution_release }} multiverse'
    - 'deb-src http://archive.ubuntu.com/ubuntu {{ ansible_distribution_release }} multiverse'
    - 'deb http://archive.ubuntu.com/ubuntu {{ ansible_distribution_release }}-updates multiverse'
    - 'deb-src http://archive.ubuntu.com/ubuntu {{ ansible_distribution_release }}-updates multiverse'
  when: ansible_distribution == 'Ubuntu'

- name: Install common packages
  apt:
    state: present
    name:
      - "nano"
      - "zip"
      - "unzip"
      - "p7zip"
      - "curl"
      - "sqlite3"
      - "tree"
      - "lsof"
      - "man-db"
      - "git"
      - "pwgen"
      - "rsync"
      - "logrotate"
      - "htop"
      - "iotop"
      - "nload"
      - "fail2ban"
      - "ufw"
      - "ncdu"
      - "mc"
      - "speedtest-cli"
      - "dnsutils"
      - "screen"
      - "tmux"
      - "apache2-utils"
      - "jq"
      - "lib32z1"
      - "moreutils"
      - "unrar"
      - "python3-virtualenv"
  ignore_errors: true

- name: Install extra packages
  apt:
    state: present
    name:
      - "run-one"
  ignore_errors: true

- name: Fetch PCI Info
  shell: "lspci -v -s $(lspci | grep -E '.*VGA.*Intel.*' | cut -d' ' -f 1) 2>/dev/null || :"
  register: lscpi_resp
  when:
    - (gpu.intel)

- name: Install 'intel-gpu-tools'
  apt:
    state: present
    name:
      - "intel-gpu-tools"
  when:
    - (gpu.intel)
    - ('i915' in lscpi_resp.stdout)

- name: Check to see if 'unrar' installed
  stat:
    path: "/usr/bin/unrar"
  register: unrar_binary

- name: Install 'unrar-free' if 'unrar' was not installed
  apt:
    name: unrar-free
    state: present
  ignore_errors: true
  when: (not unrar_binary.stat.exists)

- name: "Import 'pip.conf'"
  copy:
    src: "pip.conf"
    dest: "/home/{{ user.name }}/.config/pip/pip.conf"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: 0775
    force: true

- name: Install common pip modules
  pip:
    state: present
    name:
      - certbot
      - ndg-httpsclient
      - yq
      - apprise
      - dnspython
      - lxml
      - jmespath
      - passlib
      - PyMySQL
      - tld
    executable: pip3
  ignore_errors: true
