#########################################################################
# Title:         Saltbox: Plex Role                                    #
# Author(s):     desimaniac, l3uddz                                     #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Add DNS record
  include_tasks: "{{ resources_tasks_path }}/dns/tasker.yml"
  vars:
    dns_record: "{{ lookup('vars', role_name + '_dns_record') }}"
    dns_zone: "{{ lookup('vars', role_name + '_dns_zone') }}"

- name: Add DNS record
  include_tasks: "{{ resources_tasks_path }}/dns/tasker.yml"
  vars:
    dns_record: "{{ lookup('vars', role_name + '_webtools_dns_record') }}"
    dns_zone: "{{ lookup('vars', role_name + '_webtools_dns_zone') }}"

- name: Remove existing Docker container
  include_tasks: "{{ resources_tasks_path }}/docker/remove_docker_container.yml"

- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0775"
  with_items: "{{ lookup('vars', role_name + '_paths_folders_list') }}"

- name: Download 98-themepark
  get_url:
    url: "https://raw.githubusercontent.com/GilbN/theme.park/master/docker-mods/plex/root/etc/cont-init.d/98-themepark"
    dest: "{{ plex_paths_location }}/98-themepark.sh"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0775"
    force: true

- name: Preferences Tasks
  import_tasks: "subtasks/preferences/preferences.yml"
  when: (not continuous_integration)

- name: Docker Devices Task
  include_tasks: "{{ resources_tasks_path }}/docker/set_docker_devices_variable.yml"
  when: (gpu.intel or gpu.nvidia)

- name: Create Docker container
  include_tasks: "{{ resources_tasks_path }}/docker/create_docker_container.yml"

- name: Post-Install Tasks
  import_tasks: "subtasks/post-install/main.yml"
