#########################################################################
# Title:         Saltbox: qBittorrent | Pre-Install Tasks               #
# Author(s):     salty                                                  #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Pre-Install | Get next available port within the range of '56881-56901' # noqa fqcn[action]
  find_next_open_port:
    low_bound: 56881
    high_bound: 56901
  register: port_lookup_56881
  ignore_errors: true

- name: Pre-Install | Settings | Update 'qBittorrent.conf' config settings
  when: qbittorrent_paths_conf_stat.stat.exists
  block:
    - name: Pre-Install | Settings | Update Session\Port in 'qBittorrent.conf' config settings
      community.general.ini_file:
        path: "{{ qbittorrent_paths_conf }}"
        section: BitTorrent
        option: Session\Port
        value: "{{ qbittorrent_docker_ports_56881 }}"
        no_extra_spaces: true
        state: present
        owner: "{{ user.name }}"
        group: "{{ user.name }}"
        mode: "0775"

    - name: Pre-Install | Settings | Update WebUI\HostHeaderValidation 'qBittorrent.conf' config settings
      community.general.ini_file:
        path: "{{ qbittorrent_paths_conf }}"
        section: Preferences
        option: WebUI\HostHeaderValidation
        value: "false"
        no_extra_spaces: true
        state: present
        owner: "{{ user.name }}"
        group: "{{ user.name }}"
        mode: "0775"

    - name: Pre-Install | Settings | Update WebUI\CSRFProtection 'qBittorrent.conf' config settings
      community.general.ini_file:
        path: "{{ qbittorrent_paths_conf }}"
        section: Preferences
        option: WebUI\CSRFProtection
        value: "false"
        no_extra_spaces: true
        state: present
        owner: "{{ user.name }}"
        group: "{{ user.name }}"
        mode: "0775"

    - name: Pre-Install | Settings | Update WebUI\CustomHTTPHeaders 'qBittorrent.conf' config settings
      community.general.ini_file:
        path: "{{ qbittorrent_paths_conf }}"
        section: Preferences
        option: WebUI\CustomHTTPHeaders
        value: "{{ qbittorrent_themepark_headers if qbittorrent_themepark_enabled and global_themepark_plugin_enabled else '' }}"
        no_extra_spaces: true
        state: present
        owner: "{{ user.name }}"
        group: "{{ user.name }}"
        mode: "0775"

    - name: Pre-Install | Settings | Update WebUI\CustomHTTPHeadersEnabled 'qBittorrent.conf' config settings
      community.general.ini_file:
        path: "{{ qbittorrent_paths_conf }}"
        section: Preferences
        option: WebUI\CustomHTTPHeadersEnabled
        value: "{{ 'true' if qbittorrent_themepark_enabled and global_themepark_plugin_enabled else 'false' }}"
        no_extra_spaces: true
        state: present
        owner: "{{ user.name }}"
        group: "{{ user.name }}"
        mode: "0775"
